version: "3.8"
services:
  webapp:
    container_name: changjoh_web
    build:
      context: .
      dockerfile: .docker/webapp/Dockerfile
    ports:
      - "4433:80"
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./src:/srv/app
      - ./src/vendor:/srv/app/vendor
    restart: unless-stopped
    depends_on:
        - database
    networks:
      - app-network
  database:
    container_name: changjoh_db
    ports:
      - "3310:3306"
    image: mariadb:10.8
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./.docker/database/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=FWJhSNHEPHXM4Xg2
      - MYSQL_DATABASE=changjoh_db
      - MYSQL_USER=changjoh_user
      - MYSQL_PASSWORD=pm4LSTLhgPZujdL4
    networks:
      - app-network
    restart: unless-stopped

#Docker Networks
networks:
  app-network:
    driver: bridge